### ISSUE TITLE
Units > Groups: auto select units in a group

### ISSUE THREAD

**Issue by badbwoi** [ozonexo3/FAForeverMapEditor#133]
I'm doing units in the FAF editor now, thanks for making it way more pleasant.

Unfortunately I'm missing a quite nice GPG feature. If you select a group e.g. `Operational_Wreckage_2` the units in that group get selected. It would be nice if this could be added to the FAF editor as well.  This would be a big help in finding, selecting and editing grouped units.
![image](https://user-images.githubusercontent.com/28671151/104647402-16b41480-56b2-11eb-8a53-d5d5e3dcc624.png)

I have also created a related issue about the way units get displayed in GPG https://github.com/ozonexo3/FAForeverMapEditor/issues/108

**Comment by ozonexo3** [comment]
Added in v0.701
To select units in group you will need to double click on the group. 
With Shift key they will be added to existing selection, when holding Alt they will be removed from selection.

Single click to select might cause some issues, because to copy/paste, duplicate or create unit or move units between groups you need to click on group when you have selected units and that will change your selection.
